# Generated by Django 3.0.8 on 2020-09-29 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='added_when',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 29, 15, 30, 57, 443806, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
