# Generated by Django 3.0.8 on 2020-11-02 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201101_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.IntegerField(default=100, unique=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_made_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bid_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
