# Generated by Django 3.0.8 on 2020-09-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200929_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='descritption',
            new_name='description',
        ),
    ]
