# Generated by Django 3.0.8 on 2020-11-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201102_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='for_which_listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
    ]
