# Generated by Django 3.0.8 on 2020-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200930_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(default='Other', max_length=32),
        ),
    ]
