# Generated by Django 3.0.8 on 2020-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='created_by',
            field=models.CharField(default='User', max_length=64),
        ),
    ]
