# Generated by Django 3.0.8 on 2020-11-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201124_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.IntegerField(default=0),
        ),
    ]
