# Generated by Django 3.0.8 on 2020-10-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201022_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='owner', to='auctions.auction_listing'),
        ),
    ]
