# Generated by Django 3.0.8 on 2020-10-26 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201023_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlisted_when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
