# Generated by Django 3.0.8 on 2020-10-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_user_watchlisted_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlisted_when',
        ),
    ]
