# Generated by Django 3.0.8 on 2020-10-30 00:19

import auctions.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_user_watchlisted_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_descritption',
            field=models.TextField(default='It is a comment', max_length=2500),
        ),
        migrations.AddField(
            model_name='comment',
            name='for_what',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='when_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 30, 0, 19, 37, 306859, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='who_added',
            field=models.ForeignKey(default=auctions.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
