# Generated by Django 3.0.8 on 2020-10-30 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201030_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='who_added',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
