# Generated by Django 3.0.8 on 2020-10-30 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201030_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_descritption',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='for_what',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
