# Generated by Django 3.0.8 on 2020-10-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201030_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_descritption',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='for_what',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='when_added',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='who_added',
        ),
    ]
